version: '3.7'

services:
  frontend:
    # build: ./front
    image: ghcr.io/marnyg/frontend:latest
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 5001

  backend:
    # build: ./back
    image: ghcr.io/marnyg/backend:latest
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

